#!/bin/sh

cd devs && mkdir -p mpu itg pca && cd ..

echo "Downloading MPU..."
wget http://www.invensense.com/mems/gyro/documents/PS-MPU-3300-00.pdf -O devs/mpu/mpu_ps.pdf -o /dev/null
wget http://www.invensense.com/mems/gyro/documents/RM-MPU-3300.pdf -O devs/mpu/mpu_rm.pdf -o /dev/null

echo "Downloading ITG..."
wget http://www.invensense.com/mems/gyro/documents/PS-ITG-3050.pdf -O devs/itg/itg_ps.pdf -o /dev/null
wget http://www.invensense.com/mems/gyro/documents/RM-ITG-3050.pdf -O devs/itg/itg_rm.pdf -o /dev/null

echo "Downloading PCA..."
wget http://www.ti.com/lit/ds/symlink/pca9546a.pdf -O devs/pca/pca.pdf -o /dev/null
